baseURL: "https://justin.vc/"
title: justin.vc
theme: PaperModulo

enableRobotsTXT: true
paginate: 3

buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: justin.vc
  description: "Justin's writing(s)."
  keywords: [Blog, Portfolio, PaperMod]
  author: Justin Malloy
  images: ["<link or path of image for opengraph, twitter-cards>"]
  favicon: "JVC.png"
  DateFormat: "2006/01/02"
  defaultTheme: auto # dark, light
  disableThemeToggle: false
  EnableInstantClick: false
  TocSide: "left" # due to sidenotes - need to make interchangeable

  ShowReadingTime: false
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  showModifiedDate: true
  UseHugoToc: true
  disableSpecial1stPost: true
  disableScrollToTop: false
  comments: true
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: true

  socialIcons:
    - name: rss
      url: "index.xml"
    - name: github
      url: "https://www.github.com/brickfrog"
    - name: omg
      url: "https://jt.omg.lol"
    - name: micro-blog
      url: "https://jtm.micro.blog"
    - name: mastodon
      url: "https://social.lol/@jt"

  defaultCommentSystems:
    utterances: true

  commentSystems:
    utterances:
      repo: brickfrog/justin.vc
      issue: pathname
      label: comment
      theme: preferred-color-scheme

  logo:
    text: "justin.vc"
    #icon: "JVC.png"

  profileMode:
    enabled: false

  homeInfoParams:
    Title: "justin's musings"
    Subtitle: "code, ranting, and miscellanea"
    Omg: # for status.omg.lol on homepage
      Enabled: true # wanted to be explicit due to external calls / elsewhere use
      Name: "jt"
    MicroBlog: # for showing micro-blog posts on homepage
      Url: "https://micro.justin.vc/feed.json"
      Title: "latest-ish from micro.blog"
      Subtitle: >
        just the most recent, visit the micro.blog for more
    Content: >
      Hello! This is my site, (mostly) written/published with GNU Emacs/Hugo,
      and hosted on Github Pages for the main portion. The blogging section
      is hosted by micro.blog / omg.lol. It's primarily just a compilation of 
      blogging / tutorials I'm into. Feel free to check the about page 
      for more details. <a rel="me" href="https://social.lol/@jt"></a>

menu:
  main:
    - identifier: posts
      name: Posts
      url: /posts
      weight: 1
    - identifier: about
      name: About
      url: /about/
      weight: 2
    - identifier: now
      name: Now
      url: /now/
      weight: 3
    - identifier: archives
      name: Archive
      url: /archives/
      weight: 5
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 10
    - name: Search
      url: search/
      weight: 13
    - identifier: links
      name: Links
      url: /elfeed/
      weight: 15

assets:
  disableHLJS: true
#     favicon: "<link / abs url>"
#     favicon16x16: "<link / abs url>"
#     favicon32x32: "<link / abs url>"
#     apple_touch_icon: "<link / abs url>"
#     safari_pinned_tab: "<link / abs url>"

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false
    lineNos: false
    style: dracula
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
