baseURL: "https://justin.vc/"
title: justin.vc
theme: PaperModX
paginate: 5
enableRobotsTXT: true

buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: justin.vc
  description: "Justin's random writing on code and such."
  keywords: [Blog, Portfolio, PaperMod]
  author: Justin Malloy
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "2006/01/02"
  defaultTheme: auto # dark, light
  disableThemeToggle: false
  EnableInstantClick: false
  TocSide: 'left'

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: true
  disableScrollToTop: false
  comments: true
  hidemeta: false
  hideSummary: true
  showtoc: true
  tocopen: true
  showModifiedDate: true

  homeInfoParams:
      Content: >
        *Contemplare et contemplata aliis tradere.*

  socialIcons:
    - name: rss
      url: "index.xml"
    - name: github
      url: "https://www.github.com/brickfrog"

  commentSystems:
    utterances:
      repo: brickfrog/justin.vc
      issue: pathname
      label: comment 
      theme: preferred-color-scheme

  defaultCommentSystems:
    utterances: true

menu:
  main:
    - identifier: about
      name: About
      url: /about/
      weight: 1
    - identifier: archives
      name: Archive
      url: /archives/
      weight: 5
    - name: Search
      url: search/
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 7 
      weight: 10
    - identifier: links
      name: Links
      url: /elfeed/
      weight: 15
    - identifier: Zettel
      name: Zettelkasten
      url: https://zk.justin.vc
      params:
        external: true
       
markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        noClasses: false
        lineNos: false
        style: dracula
        # anchorLineNos: true
        # codeFences: true
        # guessSyntax: true
